BLOCK_SITE: []
DATABASE: mongodb
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://blog.junpengzhou.top/link/
  theme: common2
- link: https://noionion.top/link/
  theme: butterfly
- link: https://www.yyyzyyyz.cn/link/
  theme: butterfly
- link: https://immmmm.com/about/
  theme: common1
MAX_POSTS_NUM: 5
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - "\u8D30\u7339\u306E\u5C0F\u7A9D"
    - https://noionion.top/
    - https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
  - - "Akilar\u306E\u7CD6\u679C\u5C4B"
    - https://akilar.top/
    - https://akilar.top/images/headimage.png
  - - elizen
    - https://elizen.me/
    - https://akilar.top/images/headimage.png
    - hello.xml
